export const drawnGrid = [
  [
    { cell: 0, haveFlag: false, id: 1, isOpen: false },
    { cell: 0, haveFlag: false, id: 2, isOpen: false },
    { cell: 0, haveFlag: false, id: 3, isOpen: false },
    { cell: 0, haveFlag: false, id: 4, isOpen: false },
    { cell: 0, haveFlag: false, id: 5, isOpen: false },
    { cell: 0, haveFlag: false, id: 6, isOpen: false },
  ],
  [
    { cell: 0, haveFlag: false, id: 7, isOpen: false },
    { cell: 0, haveFlag: false, id: 8, isOpen: false },
    { cell: 0, haveFlag: false, id: 9, isOpen: false },
    { cell: 0, haveFlag: false, id: 10, isOpen: false },
    { cell: 0, haveFlag: false, id: 11, isOpen: false },
    { cell: 0, haveFlag: false, id: 12, isOpen: false },
  ],
  [
    { cell: 0, haveFlag: false, id: 13, isOpen: false },
    { cell: 0, haveFlag: false, id: 14, isOpen: false },
    { cell: 0, haveFlag: false, id: 15, isOpen: false },
    { cell: 0, haveFlag: false, id: 16, isOpen: false },
    { cell: 0, haveFlag: false, id: 17, isOpen: false },
    { cell: 0, haveFlag: false, id: 18, isOpen: false },
  ],
  [
    { cell: 0, haveFlag: false, id: 19, isOpen: false },
    { cell: 0, haveFlag: false, id: 20, isOpen: false },
    { cell: 0, haveFlag: false, id: 21, isOpen: false },
    { cell: 0, haveFlag: false, id: 22, isOpen: false },
    { cell: 0, haveFlag: false, id: 23, isOpen: false },
    { cell: 0, haveFlag: false, id: 24, isOpen: false },
  ],
  [
    { cell: 0, haveFlag: false, id: 25, isOpen: false },
    { cell: 0, haveFlag: false, id: 26, isOpen: false },
    { cell: 0, haveFlag: false, id: 27, isOpen: false },
    { cell: 0, haveFlag: false, id: 28, isOpen: false },
    { cell: 0, haveFlag: false, id: 29, isOpen: false },
    { cell: 0, haveFlag: false, id: 30, isOpen: false },
  ],
  [
    { cell: 0, haveFlag: false, id: 31, isOpen: false },
    { cell: 0, haveFlag: false, id: 32, isOpen: false },
    { cell: 0, haveFlag: false, id: 33, isOpen: false },
    { cell: 0, haveFlag: false, id: 34, isOpen: false },
    { cell: 0, haveFlag: false, id: 35, isOpen: false },
    { cell: 0, haveFlag: false, id: 36, isOpen: false },
  ],
];

export const GridWithBombs = [
  [
    { cell: 0, haveFlag: false, id: 1, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 2, isOpen: false },
    { cell: 0, haveFlag: false, id: 3, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 4, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 5, isOpen: false },
    { cell: 0, haveFlag: false, id: 6, isOpen: false },
  ],
  [
    { cell: 0, haveFlag: false, id: 7, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 8, isOpen: false },
    { cell: 0, haveFlag: false, id: 9, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 10, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 11, isOpen: false },
    { cell: 0, haveFlag: false, id: 12, isOpen: false },
  ],
  [
    { cell: 0, haveFlag: false, id: 13, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 14, isOpen: false },
    { cell: 0, haveFlag: false, id: 15, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 16, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 17, isOpen: false },
    { cell: 0, haveFlag: false, id: 18, isOpen: false },
  ],
  [
    { cell: 0, haveFlag: false, id: 19, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 20, isOpen: false },
    { cell: 0, haveFlag: false, id: 21, isOpen: false },
    { cell: 0, haveFlag: false, id: 22, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 23, isOpen: false },
    { cell: 0, haveFlag: false, id: 24, isOpen: false },
  ],
  [
    { cell: 0, haveFlag: false, id: 25, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 26, isOpen: false },
    { cell: 0, haveFlag: false, id: 27, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 28, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 29, isOpen: false },
    { cell: 0, haveFlag: false, id: 30, isOpen: false },
  ],
  [
    { cell: 0, haveFlag: false, id: 31, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 32, isOpen: false },
    { cell: 0, haveFlag: false, id: 33, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 34, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 35, isOpen: false },
    { cell: 0, haveFlag: false, id: 36, isOpen: false },
  ],
];

export const firstCellAroundEmptyGrid = [
  [
    { cell: 'bomb', haveFlag: false, id: 1, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 2, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 3, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 4, isOpen: false },
    { cell: 0, haveFlag: false, id: 5, isOpen: false },
    { cell: 0, haveFlag: false, id: 6, isOpen: false },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 7, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 8, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 9, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 10, isOpen: false },
    { cell: 0, haveFlag: false, id: 11, isOpen: false },
    { cell: 0, haveFlag: false, id: 12, isOpen: false },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 13, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 14, isOpen: false },
    { cell: 0, haveFlag: false, id: 15, isOpen: false },
    { cell: 0, haveFlag: false, id: 16, isOpen: false },
    { cell: 0, haveFlag: false, id: 17, isOpen: false },
    { cell: 0, haveFlag: false, id: 18, isOpen: false },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 19, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 20, isOpen: false },
    { cell: 0, haveFlag: false, id: 21, isOpen: false },
    { cell: 0, haveFlag: false, id: 22, isOpen: false },
    { cell: 0, haveFlag: false, id: 23, isOpen: false },
    { cell: 0, haveFlag: false, id: 24, isOpen: false },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 25, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 26, isOpen: false },
    { cell: 0, haveFlag: false, id: 27, isOpen: false },
    { cell: 0, haveFlag: false, id: 28, isOpen: false },
    { cell: 0, haveFlag: false, id: 29, isOpen: false },
    { cell: 0, haveFlag: false, id: 30, isOpen: false },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 31, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 32, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 33, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 34, isOpen: false },
    { cell: 0, haveFlag: false, id: 35, isOpen: false },
    { cell: 0, haveFlag: false, id: 36, isOpen: false },
  ],
];

export const gridWithNumbers = [
  [
    { cell: 'bomb', haveFlag: false, id: 1, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 2, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 3, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 4, isOpen: false },
    { cell: 2, haveFlag: false, id: 5, isOpen: false },
    { cell: 'empty', haveFlag: false, id: 6, isOpen: false },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 7, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 8, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 9, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 10, isOpen: false },
    { cell: 2, haveFlag: false, id: 11, isOpen: false },
    { cell: 'empty', haveFlag: false, id: 12, isOpen: false },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 13, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 14, isOpen: false },
    { cell: 5, haveFlag: false, id: 15, isOpen: false },
    { cell: 2, haveFlag: false, id: 16, isOpen: false },
    { cell: 1, haveFlag: false, id: 17, isOpen: false },
    { cell: 'empty', haveFlag: false, id: 18, isOpen: false },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 19, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 20, isOpen: false },
    { cell: 3, haveFlag: false, id: 21, isOpen: false },
    { cell: 'empty', haveFlag: false, id: 22, isOpen: false },
    { cell: 'empty', haveFlag: false, id: 23, isOpen: false },
    { cell: 'empty', haveFlag: false, id: 24, isOpen: false },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 25, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 26, isOpen: false },
    { cell: 5, haveFlag: false, id: 27, isOpen: false },
    { cell: 2, haveFlag: false, id: 28, isOpen: false },
    { cell: 1, haveFlag: false, id: 29, isOpen: false },
    { cell: 'empty', haveFlag: false, id: 30, isOpen: false },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 31, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 32, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 33, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 34, isOpen: false },
    { cell: 1, haveFlag: false, id: 35, isOpen: false },
    { cell: 'empty', haveFlag: false, id: 36, isOpen: false },
  ],
];

export const adjacentCells = [
  [
    { cell: 'bomb', haveFlag: false, id: 1, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 2, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 3, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 4, isOpen: false },
    { cell: 2, haveFlag: false, id: 5, isOpen: true },
    { cell: 'empty', haveFlag: false, id: 6, isOpen: true },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 7, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 8, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 9, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 10, isOpen: false },
    { cell: 2, haveFlag: false, id: 11, isOpen: true },
    { cell: 'empty', haveFlag: false, id: 12, isOpen: true },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 13, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 14, isOpen: false },
    { cell: 5, haveFlag: false, id: 15, isOpen: true },
    { cell: 2, haveFlag: false, id: 16, isOpen: true },
    { cell: 1, haveFlag: false, id: 17, isOpen: true },
    { cell: 'empty', haveFlag: false, id: 18, isOpen: true },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 19, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 20, isOpen: false },
    { cell: 3, haveFlag: false, id: 21, isOpen: true },
    { cell: 'empty', haveFlag: false, id: 22, isOpen: true },
    { cell: 'empty', haveFlag: false, id: 23, isOpen: true },
    { cell: 'empty', haveFlag: false, id: 24, isOpen: true },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 25, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 26, isOpen: false },
    { cell: 5, haveFlag: false, id: 27, isOpen: true },
    { cell: 2, haveFlag: false, id: 28, isOpen: true },
    { cell: 1, haveFlag: false, id: 29, isOpen: true },
    { cell: 'empty', haveFlag: false, id: 30, isOpen: true },
  ],
  [
    { cell: 'bomb', haveFlag: false, id: 31, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 32, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 33, isOpen: false },
    { cell: 'bomb', haveFlag: false, id: 34, isOpen: false },
    { cell: 1, haveFlag: false, id: 35, isOpen: true },
    { cell: 'empty', haveFlag: false, id: 36, isOpen: true },
  ],
];
